"""Adversarial-observation fuzz guard for the champion (issue #51).

A crash during an episode is an automatic loss (ADR-0006), so the single
highest-value robustness property is: *the live agent never raises, no matter how
malformed the observation is, and always hands back a legal action.* This suite
proves that property directly by firing a battery of malformed / partial /
out-of-range / wrong-typed observations at the champion **through both live
execution paths**:

- the **harness path** — ``kaggisim.strategy.make_agent`` (what the tournament,
  the promotion gate and the no-crash guard all run), exercised here with strict
  mode **off**, i.e. exactly as the ladder runs it; and
- the **submission path** — the ``main.py`` shim generated by
  ``build.package.MAIN_SHIM`` (what actually runs on Kaggle), reconstructed here
  from the real template so we test the shipped guarantee, not a paraphrase.

Both paths wrap ``act(parse(obs))`` in ``try/except Exception`` and degrade any
error to a safe PASS, so the champion's own ``act`` is left un-defensive on
purpose (ADR-0006 keeps the single choke point in the wrapper). These tests
therefore assert the *wrapped agent's* contract, which is the one the ladder
depends on.

The strict-mode control matters: ``tests/test_no_crash.py`` sets
``ROBRICULTURE_STRICT=1`` at import to make bugs surface loudly in dev, and that
env var is process-global. The ladder runs with strict **off**, so every test
here pins strict off (``monkeypatch``) to measure the real ladder behaviour
regardless of test collection order.
"""

from __future__ import annotations

import pytest

from build.package import MAIN_SHIM
from kaggisim.strategy import make_agent
from strategies import load

CHAMPION = "ranch_hands"


# --- The two live agents under test ---------------------------------------

def _harness_agent():
    """The champion as the tournament / promotion gate runs it (make_agent)."""
    return make_agent(load(CHAMPION)())


def _submission_agent():
    """The champion as the *submission* runs it: the real generated main.py shim.

    We exec the actual ``MAIN_SHIM`` template (the same string build/package.py
    writes into the tarball) so this covers the shipped code path, not a copy.
    """
    namespace: dict = {}
    exec(MAIN_SHIM.format(module=CHAMPION), namespace)  # noqa: S102 - trusted template
    return namespace["agent"]


LIVE_AGENTS = {"harness": _harness_agent, "submission": _submission_agent}


def _is_legal_action(action) -> bool:
    """A structurally legal action dict: farmer/hands/market present and sane.

    The safe-PASS fallback ``{"farmer": ["PASS"], "hands": [], "market": []}`` and
    any real turn the champion emits both satisfy this; nothing malformed should.
    """
    if not isinstance(action, dict):
        return False
    farmer = action.get("farmer")
    hands = action.get("hands")
    market = action.get("market")
    return (
        isinstance(farmer, list)
        and len(farmer) >= 1
        and isinstance(hands, list)
        and isinstance(market, list)
        and len(market) <= 10
    )


# --- The malformed-observation battery ------------------------------------

def _grid(n=10):
    return [[None for _ in range(n)] for _ in range(n)]


def _valid_obs():
    """A well-formed observation — the wrapper must pass real turns through."""
    n = 10
    return {
        "player": 0,
        "day": 0,
        "hour": 0,
        "farms": [
            {"money": 3000, "tiles": _grid(n), "farmer": [4, 4], "hands": []},
            {"money": 3000, "tiles": _grid(n), "farmer": [4, 4], "hands": []},
        ],
        "market": {"inventory": {}, "prices": {}},
        "town": {"unlocked_shops": []},
        "private": {"shed": {}, "seeds": {}, "inventories": [{}]},
    }


#: Each entry is (id, obs). These are the shapes a real evaluation could never
#: promise: wrong top-level type, missing keys, out-of-range indices, wrong-typed
#: fields, ragged grids, partial dicts. The champion's un-defensive ``act`` will
#: raise on almost all of them — the point is that the *wrapper* must not.
MALFORMED = [
    ("none", None),
    ("empty_dict", {}),
    ("list_top", []),
    ("str_top", "garbage"),
    ("int_top", 42),
    ("missing_player", {k: v for k, v in _valid_obs().items() if k != "player"}),
    ("missing_farms", {k: v for k, v in _valid_obs().items() if k != "farms"}),
    ("missing_private", {k: v for k, v in _valid_obs().items() if k != "private"}),
    ("player_out_of_range_high", {**_valid_obs(), "player": 5}),
    ("player_negative", {**_valid_obs(), "player": -1}),
    ("player_wrong_type", {**_valid_obs(), "player": "zero"}),
    ("player_none", {**_valid_obs(), "player": None}),
    ("farms_empty", {**_valid_obs(), "farms": []}),
    ("farms_too_short_for_player", {**_valid_obs(), "player": 1,
                                    "farms": [_valid_obs()["farms"][0]]}),
    ("farms_not_a_list", {**_valid_obs(), "farms": "nope"}),
    ("farms_none", {**_valid_obs(), "farms": None}),
    ("farm_missing_money", {**_valid_obs(),
                            "farms": [{"tiles": _grid(), "farmer": [4, 4], "hands": []},
                                      {"tiles": _grid(), "farmer": [4, 4], "hands": []}]}),
    ("farm_missing_tiles", {**_valid_obs(),
                            "farms": [{"money": 100, "farmer": [4, 4], "hands": []},
                                      {"money": 100, "farmer": [4, 4], "hands": []}]}),
    ("farm_missing_farmer", {**_valid_obs(),
                             "farms": [{"money": 100, "tiles": _grid(), "hands": []},
                                       {"money": 100, "tiles": _grid(), "hands": []}]}),
    ("money_is_string", {**_valid_obs(),
                         "farms": [{"money": "lots", "tiles": _grid(), "farmer": [4, 4],
                                    "hands": []},
                                   {"money": "lots", "tiles": _grid(), "farmer": [4, 4],
                                    "hands": []}]}),
    ("money_is_none", {**_valid_obs(),
                       "farms": [{"money": None, "tiles": _grid(), "farmer": [4, 4],
                                  "hands": []},
                                 {"money": None, "tiles": _grid(), "farmer": [4, 4],
                                  "hands": []}]}),
    ("tiles_is_string", {**_valid_obs(),
                         "farms": [{"money": 100, "tiles": "xxxx", "farmer": [4, 4],
                                    "hands": []},
                                   {"money": 100, "tiles": "xxxx", "farmer": [4, 4],
                                    "hands": []}]}),
    ("tiles_ragged_grid", {**_valid_obs(),
                           "farms": [{"money": 100, "tiles": [[None], [None, None]],
                                      "farmer": [4, 4], "hands": []},
                                     {"money": 100, "tiles": [[None]], "farmer": [0, 0],
                                      "hands": []}]}),
    ("farmer_out_of_bounds", {**_valid_obs(),
                              "farms": [{"money": 100, "tiles": _grid(), "farmer": [99, 99],
                                         "hands": []},
                                        {"money": 100, "tiles": _grid(), "farmer": [4, 4],
                                         "hands": []}]}),
    ("farmer_wrong_type", {**_valid_obs(),
                           "farms": [{"money": 100, "tiles": _grid(), "farmer": "44",
                                      "hands": []},
                                     {"money": 100, "tiles": _grid(), "farmer": [4, 4],
                                      "hands": []}]}),
    ("hands_not_a_list", {**_valid_obs(),
                          "farms": [{"money": 100, "tiles": _grid(), "farmer": [4, 4],
                                     "hands": "many"},
                                    {"money": 100, "tiles": _grid(), "farmer": [4, 4],
                                     "hands": []}]}),
    ("hands_of_garbage", {**_valid_obs(),
                          "farms": [{"money": 100, "tiles": _grid(), "farmer": [4, 4],
                                     "hands": [None, "x", 7]},
                                    {"money": 100, "tiles": _grid(), "farmer": [4, 4],
                                     "hands": []}]}),
    ("day_negative", {**_valid_obs(), "day": -5}),
    ("day_huge", {**_valid_obs(), "day": 10**9}),
    ("day_is_string", {**_valid_obs(), "day": "day one"}),
    ("hour_is_string", {**_valid_obs(), "hour": "noon"}),
    ("private_not_a_dict", {**_valid_obs(), "private": "nope"}),
    ("private_none", {**_valid_obs(), "private": None}),
    ("shed_is_list", {**_valid_obs(),
                      "private": {"shed": [], "seeds": {}, "inventories": [{}]}}),
    ("seeds_is_list", {**_valid_obs(),
                       "private": {"shed": {}, "seeds": [], "inventories": [{}]}}),
    ("inventories_empty", {**_valid_obs(),
                           "private": {"shed": {}, "seeds": {}, "inventories": []}}),
    ("inventories_of_garbage", {**_valid_obs(),
                                "private": {"shed": {}, "seeds": {},
                                            "inventories": [None, 3, "x"]}}),
    ("shed_wrong_value_types", {**_valid_obs(),
                                "private": {"shed": {"WHEAT": "five"}, "seeds": {},
                                            "inventories": [{}]}}),
    ("deeply_partial", {"player": 0, "farms": [{}]}),
    ("nan_ish_money", {**_valid_obs(),
                       "farms": [{"money": float("nan"), "tiles": _grid(),
                                  "farmer": [4, 4], "hands": []},
                                 {"money": float("nan"), "tiles": _grid(),
                                  "farmer": [4, 4], "hands": []}]}),
]


@pytest.fixture(autouse=True)
def _ladder_strict_off(monkeypatch):
    """Pin strict mode OFF for every test here — the ladder never runs strict.

    ``test_no_crash.py`` sets ROBRICULTURE_STRICT=1 process-globally to surface
    bugs in dev; we override it so these tests measure real ladder behaviour
    independent of test collection order.
    """
    monkeypatch.delenv("ROBRICULTURE_STRICT", raising=False)


@pytest.mark.parametrize("path", sorted(LIVE_AGENTS))
@pytest.mark.parametrize("obs_id,obs", MALFORMED, ids=[m[0] for m in MALFORMED])
def test_live_agent_never_raises_and_returns_legal_action(path, obs_id, obs):
    """No malformed observation may make a live champion agent raise; it must
    always return a structurally legal action (the safe PASS fallback)."""
    agent = LIVE_AGENTS[path]()
    action = agent(obs)  # must not raise
    assert _is_legal_action(action), f"{path}/{obs_id} returned illegal action: {action!r}"


@pytest.mark.parametrize("path", sorted(LIVE_AGENTS))
def test_malformed_input_degrades_to_the_safe_pass(path):
    """On garbage in, the wrapper degrades to the canonical safe-PASS no-op."""
    agent = LIVE_AGENTS[path]()
    assert agent(None) == {"farmer": ["PASS"], "hands": [], "market": []}


@pytest.mark.parametrize("path", sorted(LIVE_AGENTS))
def test_valid_observation_passes_through_untouched(path):
    """The fail-safe is transparent: a well-formed obs yields a real legal turn
    (the wrapper must not swallow good turns into a PASS)."""
    agent = LIVE_AGENTS[path]()
    action = agent(_valid_obs())
    assert _is_legal_action(action)
    # A fresh dawn board hires a crew, so this is a real turn, not the PASS no-op.
    assert action != {"farmer": ["PASS"], "hands": [], "market": []}


def test_champion_act_is_undefensive_by_design():
    """Guard the ADR-0006 architecture: the champion's own ``act`` is *not*
    self-defensive — malformed input raises there, and the single choke point is
    the wrapper. If this ever stops raising, the defensiveness has migrated onto
    the hot path (the design ADR-0006 explicitly rejected) and this test should
    be revisited deliberately."""
    champion = load(CHAMPION)()
    with pytest.raises(TypeError):  # None["player"] -> not subscriptable
        champion.act(None)


def test_both_live_paths_share_one_safe_pass_shape():
    """Drift guard: the harness wrapper and the submission shim must degrade to
    the *same* safe-PASS payload, so ADR-0006's 'identical local vs submission'
    guarantee can't silently diverge."""
    harness = _harness_agent()(None)
    submission = _submission_agent()(None)
    assert harness == submission == {"farmer": ["PASS"], "hands": [], "market": []}
