"""Behavioural regression guard for the baked champion genome (#110).

`strategies/champion_genome.json` ships fixed weights evolved against a
*specific* build of `neuropilot`'s controller (gate thresholds, purchase
curves, reserve constants...). Any change to that controller can silently
alter what the same shipped weights do — it has happened twice, once caught
by luck (#97) and once missed for weeks (#100). Nothing forced a
re-benchmark; remembering to run one is not a control.

This test freezes the *shipped* genome's actions on a handful of fixed,
synthetic single-turn observations, built by hand exactly like the ones in
`test_neuropilot.py`. It drives `strategies/champion_genome.json` straight
through `NeuroPilotStrategy.act` — no sim, no `genome_bench`, no 720-turn
game, no RNG, no wall-clock — so it runs in well under a second and is
byte-for-byte deterministic (ADR-0005). It is NOT a claim that the genome
plays *well*; only that it plays the *same way* it did the last time
someone looked.

One scenario (`land_reserve_below` / `land_reserve_above`) is deliberately
pinned either side of the exact money threshold at which the shipped
genome's decoded `livestock_pace` currently triggers a `BUY_LAND` order
under `_land_order`'s reserve formula (see `strategies/neuropilot.py`).
That threshold is a function of the controller's `_LAND_RESERVE` constant
(and whatever gate/curve replaces it later) — this is the exact shape of
change that caused #100, so the boundary scenario exists specifically to
catch it.

**Re-blessing — updating `GOLDEN_ACTIONS` below:**

Legitimate reasons to update it:
  - A new champion genome was promoted (`strategies/champion_genome.json`
    changed, its `meta.share`/`meta.issue` updated by a real
    `genome_bench` run per CLAUDE.md's experiment loop). Re-run the
    scenarios in `_SCENARIOS` against the new genome (e.g. paste this
    file's `_SCENARIOS` + `_ACT` into a REPL, or add a throwaway
    `print(_ACT(name))` loop) and replace `GOLDEN_ACTIONS` with the fresh
    output. The genome changing is expected and welcome — this test must
    never fight a real promotion.

NOT legitimate — this is the failure mode #100 describes, stop and read
`strategies/champion_genome.json`'s `meta.share`/`meta.win_rate` first:
  - The genome is unchanged (`strategies/champion_genome.json` untouched)
    but a controller edit (a gate, a curve, a reserve constant) turned this
    suite red. Before touching `GOLDEN_ACTIONS`, re-benchmark the baked
    genome under the new code:
    `python -m harness.genome_bench --genome strategies/champion_genome.json --games 4`
    and compare its `share` against the recorded `meta.share`. If it
    dropped, the controller change degraded the shipped agent — fix the
    controller (or re-bake a genome that recovers the share) rather than
    editing this file to make it green again.

  - #71 reinterpreted two knobs (`livestock_labor_share` -> animal-job
    weight, `fertilize_pref` -> fertilize-job weight) and replaced the
    worker-index plot mapping with job assignment. The shipped weights are
    unchanged but are now read differently, so the actions moved by design.
    Re-benchmarked before re-blessing: share 0.3390 against a 0.3760
    baseline. This drop is expected, not a regression: these weights were
    evolved against the OLD knob meanings, so some drop is the honest
    consequence of reinterpreting them; it is well above the ~0.20
    collapse band that would indicate a wiring bug, and #71's own fresh
    evolution run is the real test of the new mechanism.

  - #71's own multi-seed evolution run (10 seeds x 25 generations)
    produced a new champion: seed 7's genome, promoted 2026-08-24 with a
    verified `genome_bench --games 4` share of 0.5222 (win_rate 0.8000),
    up from the prior champion's 0.3760/0.0. `GOLDEN_ACTIONS` below was
    regenerated by running `_SCENARIOS` through the new genome. As a
    side effect, the new genome's decoded land-purchase reserve moved
    from roughly $42-43k (the prior champion) to about $23,846 (binary
    search confirmed: no `BUY_LAND` at $23,846, `BUY_LAND` at $23,847).
    `land_reserve_below`/`land_reserve_above`'s `money` inputs in
    `_SCENARIOS` were re-pinned from $42,000/$43,500 to $23,000/$24,700
    to keep bracketing the *current* threshold with roughly the same
    margin as before. Changing those two `money` values is legitimate
    specifically because the scenario pair's stated purpose is to
    bracket wherever the threshold currently sits -- freezing the old
    dollar amounts would have preserved the letter of the fixture while
    destroying what it tests (both sides would silently buy land and
    the pair would stop bracketing anything). Both boundary assertions
    (`BUY_LAND` absent below, present above) are intact and re-verified
    against the new genome.
"""
from __future__ import annotations

from strategies import neuropilot as np


def _obs(day=0, hour=0, money=3000, farmer=(4, 4), hands=(), tiles=None,
         shed=None, unlocked=("NW",), prices=None, opp_money=3000, seeds=None):
    """A minimal, fully-synthetic single-turn observation (mirrors the
    `_obs` helper in `test_neuropilot.py`)."""
    board = tiles or [[None] * 10 for _ in range(10)]
    hands = list(hands)
    return {
        "player": 0, "day": day, "hour": hour,
        "farms": [
            {"money": money, "tiles": board, "farmer": list(farmer),
             "hands": [list(h) for h in hands], "unlocked_quadrants": list(unlocked)},
            {"money": opp_money, "tiles": [[None] * 10 for _ in range(10)],
             "farmer": [4, 4], "hands": []},
        ],
        "market": {"inventory": {}, "prices": prices or {}},
        "town": {"unlocked_shops": []},
        "private": {"shed": shed or {}, "seeds": seeds or {},
                    "inventories": [{} for _ in range(1 + len(hands))]},
    }


def _mid_game_board():
    board = [[None] * 10 for _ in range(10)]
    board[4][4] = {"kind": "PLANT", "crop": "MELON", "planted_day": 30,
                    "yield_units": 5, "watered_today": True}
    board[4][3] = {"kind": "WEED"}
    board[0][5] = {"animal": "COW", "fed_today": False}
    return board


def _scattered_board():
    """Work spread across NW *and* NE, none of it on `SHED_TILE` (4, 4):
    a harvest-ready melon and a hungry cow (both #71 job kinds) plus a weed,
    with every other tile still bare and plantable (mid-season)."""
    board = [[None] * 10 for _ in range(10)]
    board[2][1] = {"kind": "PLANT", "crop": "MELON", "planted_day": 3,
                    "yield_units": 6, "watered_today": True}
    board[1][8] = {"kind": "WEED"}
    board[0][7] = {"animal": "COW", "fed_today": False}
    return board


#: Fixed synthetic observations covering the controller's main branches:
#: an untouched turn-0 board (hire + first seed buy), a mid-game board with
#: a harvestable plant, a weed, a hungry animal, fertilizer in the shed and
#: a full 5-worker crew (fertilize/sell/animal-buy/movement), a pinned pair
#: either side of the current land-purchase reserve threshold, and a
#: mid-season crew scattered across NW *and* NE (#71 review: three of the
#: other four scenarios put every worker on `SHED_TILE`, where the new
#: job-assignment mechanism happens to reproduce the old worker-index ->
#: plot mapping exactly -- this one and `mid_game_full_crew` are the only
#: two that can actually detect a future rewrite of that mechanism).
_SCENARIOS = {
    "early_game": _obs(day=0, hour=0, money=3000, unlocked=("NW",)),
    "mid_game_full_crew": _obs(
        day=50, hour=3, money=15000, farmer=(4, 4),
        hands=[(0, 0), (1, 1), (2, 2), (3, 3)],
        tiles=_mid_game_board(), shed={"MELON": 10, "WHEAT": 5, "FERTILIZER": 2},
        unlocked=("NW", "NE"), seeds={"MELON": 3},
    ),
    "land_reserve_below": _obs(
        day=10, hour=6, money=23000, unlocked=("NW",),
        hands=[(4, 4)] * 5, shed={"MELON": 20, "WHEAT": 10},
    ),
    "land_reserve_above": _obs(
        day=10, hour=6, money=24700, unlocked=("NW",),
        hands=[(4, 4)] * 5, shed={"MELON": 20, "WHEAT": 10},
    ),
    "scattered_second_quadrant": _obs(
        day=15, hour=4, money=6000, farmer=(4, 4),
        hands=[(1, 2), (8, 1), (3, 8), (6, 3)],
        tiles=_scattered_board(), shed={"MELON": 8, "WHEAT": 4, "FERTILIZER": 1},
        unlocked=("NW", "NE"), seeds={"MELON": 2, "WHEAT": 2},
    ),
}

#: Recorded actions of `strategies/champion_genome.json` on `_SCENARIOS`,
#: captured directly from `NeuroPilotStrategy(genome=<baked genome>).act`.
#: See the module docstring for when/how to regenerate this.
GOLDEN_ACTIONS = {
    "early_game": {
        "farmer": ["PASS"], "hands": [],
        "market": [["HIRE"]] * 8 + [["BUY_SEED", "MELON", 1]],
    },
    "mid_game_full_crew": {
        "farmer": ["HARVEST"],
        "hands": [["EAST"], ["EAST"], ["EAST"], ["EAST"]],
        "market": [
            ["SELL", "FERTILIZER", 2], ["SELL", "MELON", 10], ["SELL", "WHEAT", 5],
            ["BUY_LAND"],
        ],
    },
    "land_reserve_below": {
        "farmer": ["PASS"],
        "hands": [["WEST"], ["NORTH"], ["WEST"], ["WEST"], ["NORTH"]],
        "market": [["SELL", "MELON", 20], ["SELL", "WHEAT", 10],
                   ["BUY_SEED", "MELON", 6]],
    },
    "land_reserve_above": {
        "farmer": ["PASS"],
        "hands": [["WEST"], ["NORTH"], ["WEST"], ["WEST"], ["NORTH"]],
        "market": [["SELL", "MELON", 20], ["SELL", "WHEAT", 10],
                   ["BUY_SEED", "MELON", 6], ["BUY_LAND"]],
    },
    "scattered_second_quadrant": {
        "farmer": ["PLANT", "WHEAT"],
        "hands": [["HARVEST"], ["DIG"], ["NORTH"], ["PLANT", "WHEAT"]],
        "market": [
            ["SELL", "FERTILIZER", 1], ["SELL", "MELON", 8], ["SELL", "WHEAT", 4],
            ["BUY_SEED", "WHEAT", 1],
        ],
    },
}


def _act(scenario_name):
    """Run the shipped `strategies/champion_genome.json` genome on one scenario."""
    genome = np.load_champion_genome(np._LOCAL_GENOME)
    assert genome is not None, "strategies/champion_genome.json failed to load"
    strategy = np.NeuroPilotStrategy(genome=genome)
    return strategy.act(_SCENARIOS[scenario_name])


def test_matches_golden_actions_when_early_game():
    """Turn-0 board: the baked genome's hire/first-seed-buy behaviour is unchanged."""
    assert _act("early_game") == GOLDEN_ACTIONS["early_game"]


def test_matches_golden_actions_when_mid_game_full_crew():
    """Mid-game board with a full crew: fertilize/sell/buy-animal/move behaviour is unchanged."""
    assert _act("mid_game_full_crew") == GOLDEN_ACTIONS["mid_game_full_crew"]


def test_no_buy_land_when_money_just_below_reserve_threshold():
    """Just under the current land-purchase reserve threshold, the genome does not buy land.

    The #71 promotion (2026-08-24, share 0.5222) evolved a genome whose
    decoded land-purchase reserve moved to roughly $23,846 (down from the
    prior champion's ~$42-43k). `land_reserve_below`'s money value was
    re-calibrated from $42,000 to $23,000 to keep this scenario pinned just
    under the *new* threshold -- see the module docstring's re-blessing
    note for why re-pinning the bracket, not deleting the assertion, is the
    correct response here.
    """
    result = _act("land_reserve_below")
    assert result == GOLDEN_ACTIONS["land_reserve_below"]
    assert ["BUY_LAND"] not in result["market"]


def test_buys_land_when_money_at_reserve_threshold():
    """At/above the current land-purchase reserve threshold, the genome buys land.

    This scenario is the one #100 would have caught: it and
    `test_no_buy_land_when_money_just_below_reserve_threshold` are pinned
    either side of `_land_order`'s current reserve threshold for the shipped
    genome. Loosening or recalibrating that reserve (as #97 and #100 each
    did) shifts the threshold and flips one of these two assertions.
    """
    result = _act("land_reserve_above")
    assert result == GOLDEN_ACTIONS["land_reserve_above"]
    assert ["BUY_LAND"] in result["market"]


def test_matches_golden_actions_when_scattered_second_quadrant():
    """Mid-season crew scattered across NW *and* NE (none on `SHED_TILE`):
    harvest/dig/plant/move/animal-approach behaviour is unchanged.

    Unlike `land_reserve_below`/`land_reserve_above` (every worker on
    `SHED_TILE`, where the #71 job-assignment mechanism happens to reproduce
    the old worker-index -> plot mapping exactly), and `early_game` (no
    hands at all), scattered workers plus a second owned quadrant is the
    shape of state that can actually tell the #71 mechanism apart from a
    future rewrite of it.
    """
    assert _act("scattered_second_quadrant") == GOLDEN_ACTIONS["scattered_second_quadrant"]
